context_test = executable(
  'ringl-context-test',
  'context_test.c',
  dependencies: ringl_dep,
)

test('context', context_test)

buffer_test = executable(
  'ringl-buffer-test',
  'buffer_test.c',
  dependencies: ringl_dep,
)

test('buffer', buffer_test)

buffer_storage_test = executable(
  'ringl-buffer-storage-test',
  'buffer_storage_test.c',
  dependencies: ringl_dep,
)

test('buffer-storage', buffer_storage_test)

vertex_attrib_test = executable(
  'ringl-vertex-attrib-test',
  'vertex_attrib_test.c',
  dependencies: ringl_dep,
)

test('vertex-attrib', vertex_attrib_test)
